### ISSUE TITLE
App crash when running demo

### ISSUE THREAD

**Issue by hkleow** [tookan-hub/tookan-tracking-sdk-ios#3]
2017-01-24 18:37:12.884460 demoTrack[14548:10556127] [Common] _BSMachError: port 801b; (os/kern) invalid name (0xf) "Unable to deallocate send right"
fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by samneet** [comment]
HI,
Can you please specify the line off the code or the name of the file where the crash occurred .

**Comment by samneet** [comment]
Note: Please make sure that you have added MSWeakTimer framework in embedded libraries in xcode .

**Comment by kunalsethiya** [comment]
Closing this issue, due to no response.
